# Generated by Django 4.0.4 on 2022-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_delete_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='static/images/img')),
                ('email', models.EmailField(max_length=254)),
                ('Github', models.CharField(max_length=100)),
                ('LinkedIn', models.CharField(max_length=100)),
            ],
        ),
    ]
