# Generated by Django 4.0.4 on 2022-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
    ]
